version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - cp -r examples docs/source/
    post_install:
#      - pip install poetry
#      - poetry config virtualenvs.create false
#      - poetry install -E all --no-dev
      - pip install rectools[all]

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

python:
   install:
   - requirements: docs/requirements.txt

formats:
  - pdf

submodules:
  include: all
  recursive: true
