version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - cp -r examples docs/source/

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - docs
       - all

formats:
  - pdf
