version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - cp -r examples docs/source/

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

python:
   install:
   - requirements: docs/requirements.txt

formats:
  - pdf

submodules:
  include: all
  recursive: true
